### ISSUE TITLE
Search isn't discoverable

### ISSUE THREAD

**Issue by allanday** [abrt/gnome-abrt#103]
I actually didn't realise that gnome-abrt includes a search function - it was only by asking that I realised that the functionality was available. The GNOME HIG provides guidelines on how to expose search in a discoverable way: https://developer.gnome.org/hig/stable/search.html.en

Including a search button would be consistent with these guidelines, and would resolve the issue. I'd recommend placing it on the left in the header bar, above the problem list, like this:

![problem-reporting-wireframe](https://cloud.githubusercontent.com/assets/213068/5596247/2c7c6b6a-9281-11e4-82f6-330b1a5ec6f5.png)

(Ignore the other changes in that wireframe.)

**Comment by hadess** [comment]
Depends on #59
