### ISSUE TITLE
Nicer notifications

### ISSUE THREAD

**Issue by allanday** [abrt/gnome-abrt#105]
The existing notifications shown when there is a problem could do with some improvements.

 * The existing text lacks any humour, and doesn't offer an apology. As such, it doesn't help to defuse the situation that the user has found themselves in.
 * The text uses the word "package". This is an unnecessary technical detail - it should talk about components or applications.
 * The "Ignore forever" button is both ambiguous and error-prone. It isn't clear whether all problems will be ignored in the future, or just this one. If you press it by mistake or change your mind, there is no obvious way to undo.

The latest mockups provide some suggestions on how to improve them: https://raw.githubusercontent.com/gnome-design-team/gnome-mockups/master/problem-reporting/png/problem-reporting-app.png

The wording has been improved and the "Ignore forever" button has been removed. Note that the default action should be to dismiss the notification and open the problem report in gnome-abrt.

**Comment by hadess** [comment]
Fixed in abrt in 5a2141eae7f6d5ae220fe17802340bc16cd6dde8
