### ISSUE TITLE
Listen to GSetting for whether to send uReports automatically

### ISSUE THREAD

**Issue by hadess** [abrt/gnome-abrt#107]
I'm not sure whether that should live in gnome-abrt, or not. But I'd like the per-user configuration for whether to automatically send uReports to use GSettings.

This is the patch I'd apply to gsettings-desktop-schemas:
https://bugzilla.gnome.org/show_bug.cgi?id=742448

**Comment by jfilak** [comment]
If the GSetting option is supposed to control the auto-reporting in desktop session [1], we just need to add that functionality to `is_autoreporting_enabled()` in https://github.com/abrt/abrt/blob/master/src/applet/applet.c

Which one of the configuration sources would have the priority? The GSettings or the current one?

1: https://github.com/abrt/abrt/wiki/Configuration#desktop-session-autoreporting

Note: Don't forget to update https://github.com/abrt/abrt/blob/master/src/configuration-gui/abrt-config-widget.c

**Comment by hadess** [comment]
> Which one of the configuration sources would have the priority? The GSettings or the current one?

Using GSettings makes it possible disable to change the default system-wide, as well as to lock it (so it could be forced off on deployments for example).

> Note: Don't forget to update https://github.com/abrt/abrt/blob/master/src/configuration-gui/abrt-config-widget.c

I hope this would get removed instead.

**Comment by hadess** [comment]
That's now done in e1061c32f299210ab4ff897e8ed62a2827966aa4 and follow-up commits.

**Comment by hadess** [comment]
That's done in abrt master.
