### ISSUE TITLE
Ignore dialog is displayed in wrong place in GNOME Shell overview

### ISSUE THREAD

**Issue by bochecha** [abrt/gnome-abrt#109]
I just had a « kernel problem » reported, and ABRT notified me of it.

The notification offers a way to ignore similar problems in the future.

Here's what I did:

1. Open the GNOME Shell overview
2. **From the overview**, show the message tray, to reveal the ABRT notification
3. In the ABRT notification, click ignore
4. ABRT opens a dialog, asking me whether I am certain I want to ignore similar problems in the future.

At this point, I am still in the GNOME Shell overview, all the previous steps were done without leaving it.

As can be seen on the screenshot, the dialog is displayed in the wrong place.

(The dialog is also missing a title, so GNOME Shell has nothing to display in the label floating below the clickable area, but this is a more minor problem)
![abrt-dialog-wrong-place](https://cloud.githubusercontent.com/assets/272170/5972692/f25f41bc-a85d-11e4-9ea9-4d5febed5c63.png)

However, GNOME Shell still considers this window is where it should be, because the clickable area (to select the window) is in the right place, i.e **NOT** where the window actually is displayed. (this is the gray rectangle with a close button in its top-right corner, that appears when normally hovering a window in the GNOME Shell overview)

**Comment by bochecha** [comment]
One thing I forgot to note, is that if I exit the overview and re-enter it, the dialog thumbnail is displayed where it should be.

If I click the ignore button in the notification while **not** being in the overview, and only then enter the overview, the dialog thumbnail is displayed in the correct location as well.

To reproduce, you really need to open the dialog **from** the overview.

**Comment by jfilak** [comment]
It seems to me that gnome-shell doesn't like dialogues without parent. Fortunately, @hadess is working on patches for abrt-applet (the thing that displays the misbehaving dialogue) which will wipe out the dialogue.

**Comment by Catanzaro** [comment]
Nowadasy GTK+ will give you a warning if you try to create a dialog without a parent (regardless of desktop environment).

**Comment by hadess** [comment]
Fixed in commit c60f6beddd03a8c6d211cae161a80a0e2421bb54
