### ISSUE TITLE
Don't say a crash has been reported unless it has really been reported

### ISSUE THREAD

**Issue by Catanzaro** [abrt/gnome-abrt#110]
I keep getting notifications from ABRT that it has automatically reported a crash, but I'm using a computer that has no connection to the Internet, so that can't possibly be.

**Comment by Catanzaro** [comment]
The actual GUI window displays "Reported No", so it's just the notification that is wrong. But the notification seems to go away immediately so I don't know what exactly it said. (Or maybe I'm hallucinating it, but this just happened twice so probably not. :)

**Comment by jfilak** [comment]
Thank you for the report! I will try to reproduce ASAP. However, I remember that I've wirtten a code handling unavailable internet connection and you should not see the notifications at all, if your box has no internet connection (it applies only for setups with the auto-reporting on) :(

**Comment by Catanzaro** [comment]
I wiped my test system already but it was Sunday night's rawhide nightly, so if that code was present, I'd have to say it's not working. :(

**Comment by hadess** [comment]
I've rewritten that code in abrt-applet's:
It's commit c962ee3ec02a218d42000fb39edf97c4c9327e36

Let's say it's fixed, and please reopen if you still see problems.
