### ISSUE TITLE
gnome-abrt notifies me about past crashes notifications every time I login

### ISSUE THREAD

**Issue by elad661** [abrt/gnome-abrt#113]
gnome-abrt notifies me about past crashes notifications every time I login. They are always crashes which happened before, and not crashes that happened during startup. I don't like being greeted with an "oops" message and a sad face.

**Comment by jfilak** [comment]
What exactly "before" means? During boot sequence until login screen appears or old crashes that you've already seen?

**Comment by elad661** [comment]
Crashes that happened in the previous session. I didn't get a notification on the crash when it happened, I only got it after I rebooted.

**Comment by jfilak** [comment]
Can you please kill something intentionally? You can use `will_abort` binary from `will-crash` package. Because I'm not able to reproduce this bug. The output of `id` would also help.

**Comment by elad661** [comment]
I can't reproduce this again so I'm not sure what's going on, I do know it happened few times yesterday. Closing this issue, will open a new one if I see this again and have steps to reproduce.
