### ISSUE TITLE
Should avoid horizontal scrolling in the sidebar

### ISSUE THREAD

**Issue by cosimoc** [abrt/gnome-abrt#119]
In the sidebar, currently horizontal scrolling is used, which makes it harder than it should to view relevant information such as the crash date and frequency.
Instead, the sidebar could ellipsize long package names and keep the dates/counter elements in view.

![screenshot from 2015-04-03 15-00-17](https://cloud.githubusercontent.com/assets/13906/6989589/3e17411e-da12-11e4-9246-5adf88575035.png)

**Comment by andreasn** [comment]
I got this one too on my system.

**Comment by rluzynski** [comment]
The idea of wrapping the application name in 0976fa6 would conflict with the idea from #99 so either of them should be rejected. At the moment I lean to reject my own commit and accept #99 but I'd like to hear the designers' opinion.
