### ISSUE TITLE
Allow "Don't ask me again" when choosing not to upload core dump

### ISSUE THREAD

**Issue by genodeftest** [abrt/gnome-abrt#131]
When processing a crash gnome-abrt asks whether to upload the core dump or not. I never want to upload the core dump but generate a stack trace locally.
When I check "Don't ask me again" I can only click "Yes", the "No" button is disabled. Why?

**Comment by mbrysa** [comment]
Thank you for bringing this up. It's probably an old design decision. We'll address it in the next round of UI fixes.

**Comment by jfilak** [comment]
Red Hat Bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=986876

**Comment by jfilak** [comment]
In the next release of **abrt**/**libreport**, you will be able to configure the abrt client to never upload the core dump file for the remote backtrace generation, which saves your time and disk space but can be considered as security risky, and the backtrace file, needed to enter a new bug report in Red Hat Bugzilla and CentOS Bug Tracker, will be generated locally on your machine after downloading of debug info packages (potentially Gigabytes of data) into the ABRT debug info cache directory at ``/var/cache/abrt-di``.

**Comment by genodeftest** [comment]
I am running
gnome-abrt-1.2.0-2.fc22.x86_64
abrt-2.6.0-1.fc22.x86_64
libreport-2.6.0-1.fc22.x86_64
and this issue is not fixed. I still can't select the "remember my decision" checkbox and press "no". Once I check the checkbox, the "no" button is disabled.
I didn't find any switch in UI to change this behavior.

**Comment by genodeftest** [comment]
With the latest update to
gnome-abrt-1.2.0-2.fc22.x86_64
abrt-2.6.1-1.fc22.x86_64
libreport-2.6.1-1.fc22.x86_64
I can now select "don't ask me again" and press "no".
It still requires unnecessary user interaction: I still have to confirm downloading debuginfo packages, and there is no "don't ask me again" checkbox here.
