### ISSUE TITLE
Don't offer to restart GNOME Shell

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/gnome-abrt#132]
When GNOME Shell crashes, it's good that ABRT displays a notification to explain what happened after GNOME Shell restarts. But there is a Restart button on the notification. I haven't tried to click that, but it should really not be there: the process has already restarted, or you wouldn't be able to see the notification.

**Comment by rugk** [comment]
Did anyone actually try to click that? :laughing:

**Comment by msrb** [comment]
This issue should be fixed in the latest `abrt-2.17.1-1.fc38`.
