### ISSUE TITLE
ui does not start stuck high cpu

### ISSUE THREAD

**Issue by sheepdestroyer** [abrt/gnome-abrt#138]
Name        : gnome-abrt
Arch        : x86_64
Epoch       : 0
Version     : 1.2.0
Release     : 3.fc22

````

$ gnome-abrt -v
/usr/lib64/python3.4/site-packages/gi/overrides/__init__.py:313: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)

(gnome-abrt:2236): Gtk-CRITICAL **: gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed


````

No crash but cpu stuck at 90p on this task, UI does not come up

**Comment by sheepdestroyer** [comment]
my bad, 
I had a huge backlog of 5000+ unreported errors
giving enough time (a lot) to gnome-abrt was what was needed.
errors deleted and now load i 1 sec, bug can be close I guess if this long load time is not a bug by itself

**Comment by jfilak** [comment]
Thank you for the report! Not your bad, gnome-abrt should make the main window visible ASAP and indicate that data is loading. Nevertheless, I am closing this issues because this problem has already been reported (#78).
