### ISSUE TITLE
login window is too small to fit it's content

### ISSUE THREAD

**Issue by andreasn** [abrt/gnome-abrt#147]
![screenshot from 2015-11-19 00-46-08](https://cloud.githubusercontent.com/assets/209895/11258166/3732dbac-8e57-11e5-82c2-1da8e7fd2c3c.png)

The content gets cut off.

**Comment by andreasn** [comment]
This is on a hidpi screen under wayland if that helps

**Comment by jfilak** [comment]
Thanks, this issue must be fixed in libreport. Is the window scroll-able?

**Comment by andreasn** [comment]
Yep, it's possible to scroll inside it.

**Comment by andreasn** [comment]
What's libreport?

**Comment by jfilak** [comment]
> What's libreport?

It is a library used by gnome-abrt to open reports in bug tracking tools:
https://github.com/abrt/libreport/

**Comment by xsuchy** [comment]
Closing here. We will fix it in libreport.
