### ISSUE TITLE
Add more packages recognized as System

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#158]
Currently if a package is named `kernel` we display `System` in the left panel. Please add more package names to be displayed as `System`, for example `kernel-core`. What about the package `vmlinuz`? I think I saw such crash report once in Fedora 23 but the computer is not mine so I cannot access it and verify now.

@jfilak, you have shown me this issue and already started fixing so you know more details about it than I do. Also the fix seems to be easy.

**Comment by jfilak** [comment]
Hi, thank you for the ticket. There is no package `vmlinuz` in any Fedora release [1]. The `vmlinuz` file was formerly owned by the `kernel` package but it is the `kernel-core` package (`kernel-core-debug`) who owns that file now.


1: https://admin.fedoraproject.org/pkgdb/packages/?motif=vmlinuz*
