### ISSUE TITLE
"Report problem with ABRT" window needs to be redesigned

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#159]
![report-problem](https://cloud.githubusercontent.com/assets/11563230/13482269/2bdbaf76-e0ec-11e5-9302-6942f9f79089.png)

I think this window accessible via `app menu → Report problem with ABRT` needs to be redesigned. Here are the reasons why:

* The summary is prefiled with the message `A problem with ABRT`.
* It contains the word `ABRT` which is a problem according to #127. We can reword it but maybe we'd rather redesign the window.
* The message is localized.
* Users are not encouraged to edit it and provide their own summary.
* Users are not encouraged to write a report in English.
* Even if the users are aware that they should write in English it happens to them to write the description in English but leave the summary unchanged and translated into their local language.
* As a result [in Red Hat bugzilla](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=gnome-abrt&query_format=advanced) at the moment of writing we have 5 open bug reports titled `A problem with ABRT` plus 2 with the same title translated to other languages plus more English and international bug reports already closed. This is not helpful.

What I suggest:

* The initial string `A problem with ABRT` should be removed, the summary should be initially empty.
* User must be obliged to enter some summary and some description.
* User must be encouraged to write in English but it should be something like `Please write in English if possible` rather than `The details must be in English` or `Only English is allowed here`.
* The `Summary:` label is correct, probably there should also be `Details:` or `More details:` or `Description:`.

@allanday, any mockup or just suggestions, please?

**Comment by allanday** [comment]
> @allanday, any mockup or just suggestions, please?

The presence of the window seems odd in the first place, to be honest. Other applications don't have this: why should ABRT?

**Comment by rluzynski** [comment]
We had a meeting with ABRT team last month and we were talking about this window. The reasons why it exists are historical: it was added in #18 but the original idea is probably even older. Originally it was added by a former ABRT developer and its aim was to demonstrate that the gnome-abrt (or its predecessor) is so cool that it can be even used to report bugs in ABRT itself. Nowadays we all lean into removing it but nobody has made the final decision. So, @allanday if you tell us to remove this window then we will remove it. (We will have 2 less strings to deal with in #127.)

**Comment by allanday** [comment]
> Nowadays we all lean into removing it but nobody has made the final decision. So, @allanday if you tell us to remove this window then we will remove it.

I don't think it's my place to make decisions about ABRT. That said, I can't see a reason to keep it. :)
