### ISSUE TITLE
Header buttons should be adjusted with the left pane

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#165]
I'd like to suggest that the Find and Select buttons should be adjusted with the left pane and should move together with a dragging handle. See the image attached.

I'd like to hear the designers' opinion.
![panel-proposed](https://cloud.githubusercontent.com/assets/11563230/14633114/6e074d24-061c-11e6-9618-18bc7646bf4a.png)

**Comment by allanday** [comment]
Makes sense to me. I'm not really sure why the sidebar needs to be resizable though...
