### ISSUE TITLE
Include language

### ISSUE THREAD

**Issue by AnXh3L0** [abrt/gnome-abrt#167]
Can you please include Albanian in the list of LINGUAS?

**Comment by rluzynski** [comment]
Good job, @AnXh3L0 ! I can't speak any single word in Albanian but it seems to me these excerpts are problematic:

```HTML
(...) por një etiketë<i>Bugzilla</i>nuk është hapur ende.
(...) Ju lutemi konsideroni ta <b>raportoni</b>tek Bugzilla (...)
```
It will be rendered as:

(...) por një etiketë*Bugzilla*nuk është hapur ende.
(...) Ju lutemi konsideroni ta **raportoni**tek Bugzilla (...)

Are you sure there should be no spaces?

While at this, can the word "Sistemi" in Albanian be used (same as in English) both as a noun (e.g., _The **system** has crashed_) and as an adjective (e.g., _It's a **system** bug_)?

Please fix the problems in Zanata or confirm that your translation is correct.

**Comment by AnXh3L0** [comment]
Hello Rafal,

Thank you for telling me about this, I hadn't noticed the lack of spaces.I fixed it now.

About the word "sistemi", yes it can be used as both, it is gramatically correct.

Thank you.

Date: Thu, 2 Jun 2016 14:54:35 -0700
