### ISSUE TITLE
Link to project has to be updated

### ISSUE THREAD

**Issue by Jibec** [abrt/gnome-abrt#172]
In the menu "about abrt", the link is https://fedorahosted.org/abrt/ witch tells you it's not the good place to be.

![capture d ecran de 2016-06-30 14-46-52](https://cloud.githubusercontent.com/assets/474883/16489714/074fab78-3ed7-11e6-9f8c-61d70ca72cd4.png)

Please note that project is also wrong in rpm files, but it may be on purpose as it's a link to documentation https://apps.fedoraproject.org/packages/abrt

**Comment by jfilak** [comment]
Thank you for the report. Fixed by https://github.com/abrt/gnome-abrt/commit/531f1ac5c401efe37e0107833bfbcac5fc0b5648
