### ISSUE TITLE
Left panel rows have lost their padding

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#174]
Due to the changes in GTK 3.20 (Fedora 24) the current CSS selector syntax ```GtkListBoxRow { padding:12px; }```  no longer works. The result is an ugly appearance of the list of problems. The old ```GtkListBoxRow``` should be replaced with ```row```. It can be actually implemented in multiple ways:
* ```row { ...``` - simple and working but at the same time we should also mark somehow that this project requires gtk>=3.20 now;
* ```GtkListBoxRow, row { ...``` - fully portable and works in both gtk>=3.20 and gtk<3.18 although one may question if it is really required as we are going to drop the support of Fedora 23 soon (GTK 3.18.x) soon (and what about other distros like RHEL or CentOS?);
* detect the current GTK runtime version and choose the correct CSS rule - sounds like an overkill.

The fix should be backported to Fedora 24 branch and everything newer but nothing older unless it is fully portable - if it is it can be backported everywhere but there will be no visible change in those older systems.

**Comment by jfilak** [comment]
I'm all for the the second way.
