### ISSUE TITLE
No tooltips on the buttons

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#176]
Despite the `GtkAction` objects have their `tooltip` fields (and they are mostly translated) and the buttons are correctly connected with their actions with `related_action` properties the tooltips don't appear over the buttons. This is because GTK does not implement propagating the `tooltip` property from `GtkAction` to `GtkButton`. It propagates only the label and the visual state. I'm not sure if it is a bug or if it was never supposed to work. Even if it's a bug I'm afraid that a fix won't be accepted because `GtkAction` is already deprecated.

There are two possible solutions:
1. Just copy the `tooltip` property from `GtkAction`s to their respective `GtkButton`s implicitly. `gettext` framework will handle the existing translations smoothly. (At least I hope so.)
2. Be brave and migrate from the old deprecated `GtkAction` to `GAction`. But this involves the previous point as `GAction` does not handle tooltips at all.

**Comment by jfilak** [comment]
I would migrate to` GAction`.

**Comment by rluzynski** [comment]
Sounds cool! :+1:

**Comment by rluzynski** [comment]
[Here is a commit](https://github.com/rluzynski/gnome-abrt/commit/00d2cfa) in my repository. I don't create a pull request because I'm not sure it is fully correct. @jfilak, please review and feel free to comment it, rework it, or even push to master if you find it suitable. But please read these comments before.

I started working on migration to ```GAction``` but I found it too destructive (more about it later) so here I provide just a simple solution: setting the tooltips on the widgets explicitly. Note that it does not add nor change any existing string so it does not break any translation. However, it is questionable if we want all these changes:

1. It adds tooltips to all three regular buttons (```GtkButton```), I think it's OK.
2. Also it adds tooltips to all menu items. Do we want them? Is it correct according to the current Human Interface Guidelines?
3. Also it adds ```"Show filter box"``` tooltip to the search box button. Is this OK? Seems cool but no other button near it has any tooltip. Also the tooltip text is not always correct: indeed, it shows the filter box when it is not visible but also hides when it is shown. So either the tooltip text should change dynamically to ```"Hide filter box"``` or should say ```"Toggle filter box"```. But any such change would break translations which I wouldn't like to do now.
4. It does **not** add the tooltip ```"Show all known problems from all system users"``` to the ```System``` stack switch (the famous My bugs vs. System bugs list) although it might provide some useful information to the users. I have not added it because any possible implementation looked too tricky for me and again I am not sure if we want this tooltip. Note that we don't have a tooltip for ```My``` switch.

I have said in the commit comment that it closes this issue because it actually solves the original problem: makes the tooltips appear. It's probably less important from the end users' point of view if we use ```GAction``` or ```GtkAction``` inside.

Now more about why I don't like ```GAction``` so much at the moment:

1. ```GAction```, other than ```GtkAction```, does not provide labels and tooltips, they must always be set to the widgets explicitly. (More precisely about ```GtkAction```: it does support tooltips but seems to actually implement them only for the toolbar buttons.)
2. AFAIK, ```GAction``` cannot be built inside the Glade XML file, it must be built at runtime in the code (the Python code in this case). This involves many changes in multiple ```*.py``` files.
3. ```GAction``` does not seem to work correctly (or work at all) with ```GtkMenu``` so it must be also migrated to ```GMenu```, one more level of complexity.
4. With ```GMenu``` this line of code:
```python
self._builder.mi_detail.set_visible(conf['expert'])
```
probably will not work or will be tricky to implement. OTOH, do we want this feature? How useful is hiding the menu item by default and showing it only in the expert mode if the same action is available at the regular button always visible in the bottom right corner of the window?
5. Also this change reveals some no longer used code like the one related with Analyze action or All problems switch (checkbox?). I'd like to ask if this code really won't be ever used in future before I remove it.
6. ```GMenu``` does not seem to support the menu item tooltips. Shall we have to remove them in future while this patch just introduces them (or implements correctly)?

**Comment by mcatanzaro** [comment]
Note that GtkAction has been deprecated for years and is gone in GTK+ 4, so if you don't get rid of it you'll be stuck on GTK+ 3 forever.

**Comment by jfilak** [comment]
@rluzynski Feel free to make drastic changes - that's how Desktop development works in Open Source world!

**Comment by rluzynski** [comment]
I'll repeat again that it sounds really cool. Unfortunately, due to other tasks I'll be unable to do it before the F25 final release. Of course, if anybody else comes in and fixes this issue this will be even better. :-)

**Comment by mcatanzaro** [comment]
I would wait until F26 to add new tooltips so that translators have time to translate them. It's worse IMO to show tooltips that users can't read than to just have missing tooltips.
