### ISSUE TITLE
Clicking a notification has no effect

### ISSUE THREAD

**Issue by allanday** [abrt/gnome-abrt#179]
If I click one of the notifications that says that there's been a problem, nothing happens. The guidelines state that clicking the notification should open the thing that it's about - in this case, the problem report.

See:

 * https://developer.gnome.org/hig/stable/notifications.html.en
 * https://developer.gnome.org/gio/stable/GNotification.html#g-notification-set-default-action

**Comment by jfilak** [comment]
Are you sure this is a bug in gnome-abrt? I would rather blame abrt-applet. @mhabrnal can you please look into it? @xsuchy do you have capacity to work on this matter?

**Comment by allanday** [comment]
> Are you sure this is a bug in gnome-abrt? I would rather blame abrt-applet.

You tell me. All i know is that the notification doesn't perform as expected.
