### ISSUE TITLE
Suggestion: remove the Expert mode, Analyze action and other unused code

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#182]
This is how the context menu (mouse right click) in the list of problems looks like:

![gnome-abrt-menu-1](https://user-images.githubusercontent.com/11563230/29480783-43fe46a2-847b-11e7-85aa-22c441002c63.png)

But maybe not everyone knows that gnome-abrt has so called *Expert mode*:

![gnome-abrt-help](https://user-images.githubusercontent.com/11563230/29480827-96e5b2ce-847b-11e7-91dd-e491af9632c9.png)

You can switch to this mode running from the command line:

```
gnome-abrt -x
```

Its only purpose is to display the additional menu item in the context menu:

![gnome-abrt-menu-2](https://user-images.githubusercontent.com/11563230/29480857-e0eb199a-847b-11e7-9fc1-183524cfdec4.png)

But how useful is hiding this menu item inside in the *Expert mode* if exactly the same action is available by clicking the **Details** button which is visible and available all the time:

![gnome-abrt-menu-3](https://user-images.githubusercontent.com/11563230/29480896-3344b50c-847c-11e7-9b82-32f9a12256b9.png)

Further analysis shows that the Expert mode feature has been introduced by the commit 532cbd4 which was supposed to solve the issue abrt/abrt#634. But the aim of the Expert mode was not to control the visibility of the Details menu item but to control the Analyze action (menu item, button, or possibly anything else). Later most (all?) of the Analyze related UI has been removed (probably in the commit f5eb93f) but the ```GtkAction``` object and its code still remains.

So my suggestions are:

* Please check if there is still a reason to have an Expert mode, an Analyze action, and hidden Details menu item (while there is a button which does exactly the same).
* Remove the Expert mode.
* Make the Details menu item always visible (no need to hide it).
* Remove all remaining unused code related with the Analyze action.

I'm OK implementing these changes (although newcomers are welcome), just tell me if my analyze :-) is correct.

Introducing these changes will simplify fixing the issue #176 (the new ```GAction```/```GMenu``` API makes controlling the visibility of individual menu items difficult).

**Comment by jfilak** [comment]
Rafal, you are 100% correct. Go ahead with the implementation.
