### ISSUE TITLE
KDE/Widows-like report wizard.

### ISSUE THREAD

**Issue by ghost** [abrt/gnome-abrt#200]
Sometimes programs don't crash but there is still a bug or a missing feature. It's currently very tedious to search for the proper place to file reports, especially for new users.

I know Gnome, unlike KDE and Windows, will never implement this, but maybe the problem reporter can allow users to file free-form bug reports directly for each supported package?

**Comment by ernestask** [comment]
> I know Gnome, unlike KDE and Windows, will never implement this

Please refrain from making such blanket statements.

What is being requested here, exactly? A different frontend for reporting problems? What are free-from bug reports? You can add text using the current reporting wizard.

**Comment by msrb** [comment]
This is out-of-scope for ABRT.
