### ISSUE TITLE
FTBFS on Fedora 28

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#208]
Currently it is impossible to build the most recent version of ```gnome-abrt``` from source on Fedora 28 because since the commit ad0630bd64397b0f7e7ee8cae4ef98a620f547a5 it requires pygobject-3.0 >= 3.29.1 while Fedora 28 provides 3.28.3. What can we do to fix it?

Please note that Fedora 28 is still alive and will be for the next ~4 months.

**Comment by ernestask** [comment]
I have branched master (sans breaking changes) into `f28`. I also included the string changes there, which may or may not be undesirable. We can backport things until we finally retire the branch.
