### ISSUE TITLE
Please spell "D-Bus" correctly

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#209]
```gnome-abrt``` is not a part of the GNOME Project but as we are touching strings already (and providing some new work for the translators) let's follow the [Typography Guidelines](https://wiki.gnome.org/Design/OS/Typography). That means, let's use the modern Unicode quotes and other punctual characters.

While at this, please spell ```"D-Bus"``` correctly.

I will open a new pull request very soon.

**Comment by ernestask** [comment]
> `gnome-abrt` is not a part of the GNOME Project

I don’t think this matters at all. Our target environment is GNOME and GNOME designers have gotten involved before. It only makes sense to follow the guidelines.
