### ISSUE TITLE
In Fedora Rawhide header buttons are not aligned with the left pane

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#213]
See the picture. I believe this is due to the recent changes in GTK3 and/or GNOME 3.

See also: #165.

![virtualbox_rawhide_05_02_2019_12_24_06](https://user-images.githubusercontent.com/11563230/52270832-5c9ec480-2942-11e9-95ab-9e7011dff0ab.png)

**Comment by ernestask** [comment]
Ugh, I thought I had managed to get it working.

**Comment by ernestask** [comment]
I’ll try to take a dual-header bar approach (à la Contacts), which would also help get rid of that *cough* sizing code.

**Comment by ernestask** [comment]
Which also means that I will probably have to get rid of the title label. It provides no value, anyway, as far as I can see.

**Comment by rluzynski** [comment]
I think that the sizing code needs just a minor fix and the bug is somewhere around https://github.com/abrt/gnome-abrt/blob/master/src/gnome_abrt/views.py#L1073:

```python
        # Calculate the position of the box relative to its parent
        padding = self.get_box_header_left_offset()

        ...

        # This assumes that the right padding is the same as the left padding
        self.box_panel_left.set_size_request(
                sum_width + 2 * padding, -1)
```
This code falsely assumes that the left offset of a widget is its padding. Now it's not just padding but also additionally the menu button size (including its margins and padding).

I'm sorry for not providing the solution immediately, my resources (time etc.) are limited.

**Comment by ernestask** [comment]
Looks like that might be the better option here, though I would prefer keeping sizing code inside GTK when not writing custom widgets.
