### ISSUE TITLE
The new application menu (GNOME) looks bad

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#215]
Something wrong has happened with the application menu (the one displayed in GNOME and similar desktop environments). Previously it had the following items:

* **Preferences** - showing the preferences dialog
* **About** - showing the about box
* **Quit** - closing the application

I believe you can still see this in Fedora 28 and 29.

Now in Rawhide I can see:

* **Problem Reporting** (what does it do?)
* **New Window** (what does it do?)
* Huge vertical gap (why?)
* **Show Details** (opens gnome-abrt page in [GNOME Software](https://wiki.gnome.org/Apps/Software))
* **Quit** - works as expected

**Comment by ernestask** [comment]
A screenshot or two would help.

**Comment by allanday** [comment]
The behaviour in gnome-shell has changed: the menu is now generated by gnome-shell itself (see https://gitlab.gnome.org/GNOME/gnome-shell/issues/624).

> **Problem Reporting** (what does it do?)

That's probably https://gitlab.gnome.org/GNOME/gnome-shell/issues/968

> **New Window** (what does it do?)

This opens a new window. I believe that this action comes from gnome-abrt.

> Huge vertical gap (why?)

This is just how groups of menu items are presented. If you think the gap is too big, or that should look different, just file an issue.

**Comment by rluzynski** [comment]
Thank you, @allanday, your explanations are helpful.

> > Huge vertical gap (why?)
>
> This is just how groups of menu items are presented. If you think the gap is too big, or that should look different, just file an issue.

This gap disappeared after today's update. That means the issue has already been fixed.

So, according to what you said, whatever issues are here, they belong to GNOME Shell, and an application can (or should) provide its own fallback menu (see: #216), is that correct?

For the record, here are the up-to-date screenshots:

![gnome-abrt-menu-comparison](https://user-images.githubusercontent.com/11563230/52752377-e01b7e00-2ff2-11e9-8a87-985bf0aa490f.png)

**Comment by allanday** [comment]
> an application can (or should) provide its own fallback menu (see: #216), is that correct?

Applications should move the menu items from their app menu to other locations. Design guidelines can be found [here](https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement).
