### ISSUE TITLE
No more traditional menu for non-GNOME environments?

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#216]
The new design introduced since the commit ad0630bd64397b0f7e7ee8cae4ef98a620f547a5 removes detection if the current desktop environment is GNOME (or similar) and displays the application menu or not. For non-GNOME desktops (MATE, KDE, etc.) there was no headerbar and instead of the global application menu a traditional window menu bar was added which allowed an access to the same menu items as in the application menu in GNOME.

Was that intentional? I don't mind if the designers want to display the headerbar and make the application look GNOME-like even in non-GNOME environments. Are you sure that the same menu items are available also in non-GNOME environments, or they are so unimportant that we may not display them at all? If that's true then the file ```src/gnome_abrt/desktop.py``` can be removed because it has no purpose now (there is only one function inside and it is not used now). Otherwise, please revert the change at least partially.

**Comment by ernestask** [comment]
This is really gnome-abrt, not everything-and-the-kitchen-sink-abrt. Please provide concrete examples where things don’t work (client-side decorations are not supported, and application menu button is not shown), and then we can go from there.

As it is right now, the traditional menu will not return, but something will need to appear in the header bar to cope with the removal of the global application menu in the top bar. Possibly one of the beloved hamburger menus (or just a button to open preferences, as “about” and “quit” need not appear anymore, if I remember correctly).
