### ISSUE TITLE
Does gnome-abrt work in Wayland?

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#217]
There is a piece of code in gnome-abrt which checks if an Xserver is available and quits immediately if it is not. Now I wonder: what if we have Wayland and there is no Xserver deliberately? Do we really need to check if an Xserver is available? Is there any reason why gnome-abrt should not work in Wayland? Aren't the default error handling routines sufficient if a user runs gnome-abrt in non-graphic environment? Can we just drop this piece of code?

The checking code is in ```src/gnome_abrt/wrappers/xserver_check.c```.

**Comment by ernestask** [comment]
Should work fine with things like XWayland, which includes GNOME, but it indeed makes little sense.

**Comment by ernestask** [comment]
Especially given that GTK itself will not initialize properly without a display.
