### ISSUE TITLE
Localization does not work with the new GUI implementation

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#220]
All strings loaded from the XML GUI remain untranslated. Only those widgets which are created or modified later are translated.

How to test:

* Use Fedora Rawhide, it currently contains the most up-to-date version.
* Launch ```gnome-abrt``` in any non-English and highly complete locale. Currently ```pl_PL``` and ```uk_UA``` are 100% complete, many others are above 90%.
* Some widgets remain English: most visible are ```Delete``` and ```Report``` buttons, the title ```Problem Reporting``` and more.

This issue is not the same as #210 because the other issue was about the translatable strings completely missing from the ```*.pot``` file. Now translations are present and complete but still not working.

**Comment by ernestask** [comment]
Created https://github.com/abrt/gnome-abrt/pull/221.
