### ISSUE TITLE
Update app icon

### ISSUE THREAD

**Issue by jimmac** [abrt/gnome-abrt#224]
With the 3.32 release of GNOME, the application icon style guidelines [have been updated](https://developer.gnome.org/hig/stable/icon-design.html.en), embracing a more geometric look with vivid colors. The number of sizes necessary has also been reduced. I'd like to propose an updated icon, keeping you in the loop from the start of the design process.

**Comment by jimmac** [comment]
The obvious start is working off the current symbolic shape --
![Template](https://user-images.githubusercontent.com/14821/54547736-a13c6780-49a6-11e9-9442-8cf8e2ceadda.png)

**Comment by jimmac** [comment]
Going with the current fullcolor silhouette:

![Template 2](https://user-images.githubusercontent.com/14821/54548413-26744c00-49a8-11e9-80b9-b43bcac11472.png)

**Comment by jimmac** [comment]
If you were willing to revisit the metaphor, here's a couple of ideas:

![Template 4](https://user-images.githubusercontent.com/14821/54550760-f3808700-49ac-11e9-9fc3-fdadf54d9893.png) (Windows and OSX system application hangs are usually accompanied with the waiting cursor).

![Template 3](https://user-images.githubusercontent.com/14821/54550823-0eeb9200-49ad-11e9-8965-59919539620f.png) (A fedora-like pill with the default spinner hinting to a similar system hang like above).

**Comment by ernestask** [comment]
But those aren’t really for hangs, now, are they? It’s just a busy cursor/spinner to indicate activity.

**Comment by jimmac** [comment]
It's certainly closer to application issues than a signal light used to warn traffic about emergency vehicles. I assume you want to stick to the metaphor then? Or are you open to look for alternative metaphors?

**Comment by xsuchy** [comment]
FYI: We have revisited the logo 2 years ago when we printed stickers. We had a lot of proposal and we chosen these two winners:
https://github.com/abrt/abrt/blob/master/icons/abrt_hexa_stickers.svg

**Comment by jimmac** [comment]
Sticking with the current metaphor, I prefer the conical shape to the round one:

![abrt1](https://user-images.githubusercontent.com/14821/54933661-5fb73980-4f1d-11e9-9d99-d368944547e2.png)

![abrt2](https://user-images.githubusercontent.com/14821/54933666-62b22a00-4f1d-11e9-86b4-2c6f9854beff.png)

**Comment by xsuchy** [comment]
I prefer to not change the icon. But if you are altering all Gnome icons, then it makes kind-of sense and I will have no objection to PR.

From these two I like the conical shape as well. Just that the exclamation seems too narrow.

**Comment by mkutlak** [comment]
Closed by https://github.com/abrt/gnome-abrt/pull/225
