### ISSUE TITLE
Missing and mismatched icons

### ISSUE THREAD

**Issue by mkutlak** [abrt/gnome-abrt#226]
- Icons in `gnome-abrt-1.2.8` are missing in the navigation bar 
  (it should also say `Problem Reporting` instead of `abrt`/`gnome-abrt`)
- Icons are mismatched in main window and reporting window

See:
![gnome_abrt_1_2_8](https://user-images.githubusercontent.com/24898105/58315928-c02a0080-7e12-11e9-8950-4dd420019c03.png)

**Comment by ernestask** [comment]
Yeah, the missing icon is probably because of the renaming of files. Will look into it.

**Comment by ernestask** [comment]
`report-gtk` lives in libreport; can you create an issue there?

**Comment by SDey96** [comment]
I noticed it as well today.

**Comment by AsciiWolf** [comment]
The icon in the About dialog is also the old one.

**Comment by AsciiWolf** [comment]
On latest Rawhide with gnome-abrt-1.2.8, the menu icon is completely missing:
![Missing icon](https://user-images.githubusercontent.com/2339930/61877899-31a82d00-aef0-11e9-9fa0-c8e52de4ae3e.png)

**Comment by ernestask** [comment]
Just needs a new release. I didn’t tag one with all the fixes.
