### ISSUE TITLE
Wording of unreportable kernel-core errors

### ISSUE THREAD

**Issue by ferdnyc** [abrt/gnome-abrt#235]
> The backtrace does not contain enough meaningful function frames to be reported. It is annoying but it does not necessary signalize a problem with your computer. ABRT will not allow you to create a report in a bug tracking system but you can contact kernel maintainers via e-mail.

"Signalize" is not a real word.

**Comment by ferdnyc** [comment]
("Signify" would be closest, but I'd suggest something like "indicate" as being a better fit to the intent of the message.)

**Comment by ernestask** [comment]
https://en.wiktionary.org/wiki/signalize
