### ISSUE TITLE
Report button not disabled after startup

### ISSUE THREAD

**Issue by mgrabovsky** [abrt/gnome-abrt#242]
Upon startup, the first problem in the list of problems is selected. If the problem is not reportable, the Report button should be disabled. Currently, the button stays sensitive after startup if the first problem is non-reportable.

The attached screenshot illustrates the UI state immediately after starting the application.

![Screenshot from 2019-11-15 17-21-54](https://user-images.githubusercontent.com/134321/68958644-c8b13180-07cc-11ea-8b8c-1ec04c64831c.png)

**Comment by ernestask** [comment]
Good catch.
