### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [abrt/gnome-abrt#244]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by ernestask** [comment]
Project on Zanata locked, but otherwise things are the same as here: https://github.com/abrt/retrace-server/issues/283#issuecomment-572047887

**Comment by Jibec** [comment]
could you please:

- remove empty po files (use file size or "pocount" from "translation toolkit")
- commit pot file

**Comment by ernestask** [comment]
Done.

**Comment by Jibec** [comment]
configuration is done: 
https://translate.stg.fedoraproject.org/projects/abrt/abrt-gnome


LINGUAS will be updated by Weblate

PO files will be updated by Weblate when POT is updated

Weblate will use Git Squash by author to limit the number of commits

I enabled language consistency between your components (if you add a 
language in one component, it will add it to all components)

**Comment by rluzynski** [comment]
The commit c17481c19866080abba470ada6d866bb93bf8407:

* Added 15 new languages which were not needed because they don't have any translations (later translations were added for 1 of those new languages). Should we remove them? Should they stay in the source code but should they be ignored by build scripts?
* Did not update the ```LINGUAS``` file. Should we update it manually?
* The first line of the commit message says that ```zh_HK``` was added. Other languages are listed only inside. Can this be improved somehow? It would be nice to list them all in the first line or a list could be ellipsized if it is too long.

**Comment by ernestask** [comment]
Commits are squashed, that’s why the message is like that.

**Comment by ernestask** [comment]
And are “empty” translation files a problem? I hardly believe that gettext is going to use empty strings instead of the original.

**Comment by ernestask** [comment]
I uninstalled the squash addon. It has some settings for tweaking, but let’s see how things look without it.

**Comment by rluzynski** [comment]
It's a minor problem. Nothing that impacts the end user. The only problem is that they consume the disk space. Unless it is a problem in Weblate which should be addressed I don't insist on removing the empty translations.

**Comment by ernestask** [comment]
More likely that it’s Weblate. I explicitly got rid of the empty ones we already had per Jean-Baptiste’s request. Let me look into that and get back to you.

**Comment by Jibec** [comment]
I feel like no more work is to be done here, I don't really understand why you disabled the squash feature, but as long as you are happy, that's perfect

any support request has to be done on translation mailing list: https://lists.fedoraproject.org/archives/list/trans%40lists.fedoraproject.org/

**Comment by Jibec** [comment]
and, LINGUAS file is only updated by weblate when weblate itself add new languages. If some where added before and missing, weblate won't do anything

**Comment by ernestask** [comment]
> and, LINGUAS file is only updated by weblate when weblate itself add new languages. If some where added before and missing, weblate won't do anything

Sounds like a cop-out to me.

**Comment by Jibec** [comment]
I agree with you, but it's what Weblate dev told me about how it work. I'll see him Sunday and ask him to improve the plugin. I'll remember to open a bug about it also.

**Comment by ernestask** [comment]
I realize that and it’s pretty much irrelevant at this point, since I went ahead and copied the Cockpit setup, which automatically updates LINGUAS. Other maintainers may not have that, so it would be great if the developers can be, say, more accommodating.

In any case, thank you.

**Comment by Jibec** [comment]
I discovered this lack of feature with you. I assume the best is to disable the add-on in your component in Weblate. As project admin, you should be able to do so. Tell me if you need guidance.
