### ISSUE TITLE
Improve the build scripts

### ISSUE THREAD

**Issue by rluzynski** [abrt/gnome-abrt#248]
I believe 1.2.10 release is just around the corner. There were problems building the downstream RPM during two recent releases because of some files missing in the upstream tarball. Some of them were fixed, for example in the past the current version number was read from the git tags which were missing from the tarball (this was fixed in the commit f7ca818132307a6529179f17aa0d3d23da059454). Other problems are still there. See also: [a downstream workaround forcing the ```*.gmo``` files to be rebuilt](https://src.fedoraproject.org/rpms/gnome-abrt/c/bc08bd402f5a9c1d2cb220d080b29859cd46ba50?branch=master).

Let's consider this problem fixed if one can download a tarball automatically created by GitHub (not by ```make release``` script) and build the release from it, including building the RPM using the unmodified ```*.spec``` script (with patches and workarounds removed).

**Comment by ernestask** [comment]
This will only happen if we start using autoreconf downstream, which is against the Fedora guidelines. Until then, we need to minimize translation patching and make sure to upload release tarballs generated from the release target.

**Comment by rluzynski** [comment]
> This will only happen if we start using autoreconf downstream, which is against the Fedora guidelines.

Is there anything wrong with the ```*.spec``` file? Would you mind improving it, maybe here upstream?

> Until then, we need to minimize translation patching

I think it's nice if translators provide or improve their translations even after the release and can see their contributions in the released versions ASAP.

> and make sure to upload release tarballs generated from the release target.

If you mean "change the scripts so it's impossible to skip uploading the release tarball" then this is exactly what I mean. If you mean "tell all the developers not to make the same mistake ever in the future" then as you can see it did not work in the past. Even if you do not make this mistake, what if you quit the project and new people come and have no idea about these additional steps?

**Comment by ernestask** [comment]
Nothing wrong with the spec file, just the entire setup makes for some manual work. I’d like to move to Meson, which would make things simpler, if I’m not overlooking something.

As for including translation updates, I’m thinking of branching for each release of Fedora, so that we don’t get unwanted features in older releases and so that we get translation updates upstream and all you need is to just build from a git commit/tag.

The idea about improving release scripts is great, I might just look into doing that.

**Comment by ernestask** [comment]
I think this is obsoleted by the switch to Meson.
