### ISSUE TITLE
dialog with the bug details

### ISSUE THREAD

**Issue by mozeq** [abrt/gnome-abrt#266]
Opened '20110411T13:45:27' by jmoskovc as https://fedorahosted.org/abrt/ticket/209

dialog that will show the bug status, links, comments and more info:
- we discussed this some time ago and for now I think only the following info makes sense for us:
  - bugzilla status (NEW, ASSIGNED, CLOSED, etc ...)
  - links to other places where this bug was reported (if any)
- things like bz comments can be implemented if there will be more users to use it, but those can be viewed by simple clicking on the bug link and I'd like to avoid implementing bz interface in gtk, because then users start asking for change status using abrt, add comments, etc... so I would stick with strictly '''read-only''' interface

**Comment by xsuchy** [comment]
This would be nice, but require too much work. And IMO not worth the work. We have browsers for that nowadays.
