### ISSUE TITLE
Show the package name/application name from desktop file, and a description

### ISSUE THREAD

**Issue by mozeq** [abrt/gnome-abrt#269]
Opened '20110408T18:14:03' by vda as https://fedorahosted.org/abrt/ticket/200

Show the package name (and/or application name from desktop file), and a description of it, in the first screen of the reporting wizard (users might not understand the error or in what component it was, eg. you can't expect a new linux user to know what a kernel oops is and what's the purpose of gnome-settings-deamon).

NAK. We do not try to work with idiot users. If user doesn't know what oops is (and perhaps what kernel is), his reports run high risk to be useless.

**Comment by xsuchy** [comment]
This will likely never be implemented.
