### ISSUE TITLE
how old a problem is may be self-contradictory

### ISSUE THREAD

**Issue by Nick-Levinson** [abrt/gnome-abrt#294]
"PackageKit . . . . encountered a problem and could not continue." This was first detected "a month ago". But the left panel, under System, says "2 months ago".

I don't know what caused a problem with PackageKit a month or two ago, so I don't know how to replicate this, and so I don't know if this always happens.

The PackageKit version was 1.1.13-3.fc32.x86_64 (according to Problem Reporting). The Problem Reporting version is 1.3.6. The platform is Fedora 33 Linux, kept evergreen, on x86_64 hardware.

I hadn't clicked on the header in a while, so I hadn't noticed the report earlier.

**Comment by mgrabovsky** [comment]
We're tracking this issue in #91.

**Comment by Nick-Levinson** [comment]
I'm reopening or will try to. It was closed because the issue was being tracked as being about formatting, but this seems to be a substantive discrepancy, not a formatting problem.

While cold-rebooting, Problem Reporting (a/k/a abrt) said Gnome Software crashed 2 weeks ago. I don't remember that crash, I use the laptop daily, and I run the Software app briefly almost daily. If it says it crashed, I guess it crashed, but how could a crash of 2 weeks ago have been first detected just 9 days ago despite nearly daily use of the app? Sounds like a bug somewhere.

By contrast, abrt often reports that kernel-core crashed (with auto-recovery) about a minute before, when I cold-reboot. So the problem depends on what crashed.

STR: Unknown, since a crash is required and it has to be a crash that yields a discrepancy.

I'm running Fedora 33 Linux, kept evergreen.

Related: https://github.com/abrt/gnome-abrt/issues/91 and https://github.com/abrt/gnome-abrt/issues/56

An attachment is being attempted by pasting a screenshot below.

x-special/nautilus-clipboard
copy
file:///home/nick/Documents/working%20files/comp%20issues/abrt,%20Problem%20Rptg/Screenshot%20from%202021-03-25%2019-44-02.png
