### ISSUE TITLE
user space crashes are assigned to kernel-core and cannot be reported

### ISSUE THREAD

**Issue by cmurf** [abrt/gnome-abrt#295]
[Fedora bug equivalent](https://bugzilla.redhat.com/show_bug.cgi?id=1936288)

gnome-abrt-1.3.6-2.fc34.x86_64
abrt-2.14.5-2.fc34.x86_64

Description of problem:  
gnome-abrt shows multiple crashes attributed to the kernel-core, which are not kernel crashes and they can't be reported to the retrace server or locally processed

Actual results:  
    *User space crash is assigned to kernel.
    *Crash coredump is not collected.

Expected results:  
    *User space crash should not be assigned to the kernel; and a coredump should be collected so it can be submitted to the retrace server or locally processed.

Downstream bug report contains this same attachment, which is compressed abrt/oops files
[abrt.tar.gz](https://github.com/abrt/gnome-abrt/files/6099199/abrt.tar.gz)

**Comment by mcatanzaro** [comment]
Maybe related to https://github.com/abrt/abrt/issues/1386?

**Comment by mzidek-gh** [comment]
Yes this is a duplicate of https://github.com/abrt/abrt/issues/1386 Closing this one.
