### ISSUE TITLE
Bug Date Showing As Last Year.

### ISSUE THREAD

**Issue by RetiredLake9230** [abrt/gnome-abrt#312]
Happy New Year!

Not sure if this is a bug, either way is very misleading. If I had a bug on New Year's Eve, it should not say Last Year, rather 3 days ago like it says in the details pane. Basically, the error in the list should match the one in the details pane.

![Screenshot from 2022-01-03 12-10-47](https://user-images.githubusercontent.com/29177725/147975793-48c198a9-f2df-4139-9d32-545525d22115.png)

**Comment by hlovdal** [comment]
Have you ever had the misfortune of arriving at a web forum/mailing archive where every single post is just dated "5 years ago" without any indication of when the post were made (did the reply come the same day or months later? Who knows?). This is just as bad.

And changing "last year" to something else like "10 days ago" does *not* fundamentally help.

**Always** present the [full date](https://en.wikipedia.org/wiki/ISO_8601), where relative "X ago" time indications can be presented *in addition*.

STOP REMOVING USEFUL INFORMATION!

![Screenshot_20220109_000231](https://user-images.githubusercontent.com/3678550/148682632-e4dd643d-a8f6-4249-94a7-8c975a73385a.png)

**Comment by RetiredLake9230** [comment]
1. If the first detected time is already correct in the details pane, why can't that time also show underneath the error instead.
2. That was my bad. The error appeared on New Year's eve (2021-12-31) and the screenshot and post were made 3 days after (2022-01-03).

**Comment by mgrabovsky** [comment]
Thanks for your report. In this case, it does indeed look like there should be a better way to present the information. We will hopefully make some changes in this direction in the next release of gnome-abrt.

On a related note, we already have a similar bug report from quite a while ago: #91.

**Comment by RetiredLake9230** [comment]
I suggest closing this issuse.

**Comment by RetiredLake9230** [comment]
I suggest closing this issue as a comment in the issue that you mentioned also talked about this same bug but 6 years ago, and that comment goes more in depth than mine. Therefore I suggest working on that issue instead.
