### ISSUE TITLE
After updating the kernel, grub menu was not updated

### ISSUE THREAD

**Issue by Seant1125** [abrt/gnome-abrt#324]
I updated fedora kernel belows:
sudo dnf upgrade
When the system is updated,  I reboot the system. And I found the new kernel has not shown in grub menu.
To solve this problem, I did that:
~ sudo sed -i 's/GRUB_ENABLE_BLSCFG=true/GRUB_ENABLE_BLSCFG=false/g' /etc/default/grub
~ sudo grub2-mkconfig -o /boot/grub2/grub.cfg
~ sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
But how to fix this bug? Please help.

**Comment by mgrabovsky** [comment]
Hi, this is the bug tracker for GNOME ABRT only. To ask general questions regarding Fedora, please use the [Ask Fedora website](https://ask.fedoraproject.org/).
