### ISSUE TITLE
Make gnome-abrt openSUSE-aware

### ISSUE THREAD

**Issue by jfilak** [abrt/gnome-abrt#34]
Blocks abrt/abrt#589

**Comment by xsuchy** [comment]
@jfilak  What is status of this issue? Is it done or we still need something?

**Comment by jfilak** [comment]
It is not merged into the branch master. There are some missing parts but I did a poor documentation job. This issue deservers a special wiki page.

**Comment by xsuchy** [comment]
not going to happen without external contribution.
