### ISSUE TITLE
Use GtkHeaderBars

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/gnome-abrt#70]
At least when running in GNOME, every window and dialog use a GtkHeaderBar and buttons should usually be be placed in the header bar (as seen in the Oops mockups).

Optionally, you might not want to not use header bars when not running in GNOME. https://wiki.gnome.org/HowDoI/Dialogs describes the best way to achieve that.

**Comment by ernestask** [comment]
This is already done, no?

**Comment by mcatanzaro** [comment]
Only for the main view, not yet for bug reporting windows.

**Comment by ernestask** [comment]
Those come from libreport, so no point in keeping this open. The UI parts should be moved out of there first, and that deserves a separate issue (probably one already exists).
