### ISSUE TITLE
Remove Preferences

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/gnome-abrt#73]
I took a look through the Preferences available through the app menu Preferences item. I think we want the user to be able to configure nothing here, except for Bugzilla name/password, so I would just remove the whole thing: it's almost entirely confusing technical details that users should not be able to see. If there's anything else important that I missed, it should be merged into the other configuration dialog (the dialog in issue #68).

It's particularly problematic that the user has to configure everything separately for each type of problem report. It doesn't seem likely that I would want to use a different Bugzilla username for ccpp reports than for Python reports, for example.

**Comment by mcatanzaro** [comment]
Nowadays this is inconsistently called Preferences in the app menu but Configuration in the window itself. I would still remove it. Can be configured via CLI in the unlikely event someone is running their own retrace server etc.

The default window size is also way too small to actually see any of the content:

![screenshot from 2019-01-17 16-44-08](https://user-images.githubusercontent.com/1424966/51353779-2672d100-1a77-11e9-8a50-7f35beb497f2.png)

**Comment by xsuchy** [comment]
Closing in favor of https://github.com/abrt/gnome-abrt/issues/49

**Comment by RokeJulianLockhart** [comment]
> It's particularly problematic that the user has to configure everything separately for each type of problem report. It doesn't seem likely that I would want to use a different Bugzilla username for ccpp reports than for Python reports, for example.

WikiMedia's federated preferences demonstrate how to implement this. [^1]

[^1]: [`en.wikipedia.org/wiki/Special:GlobalPreferences`](https://en.wikipedia.org/wiki/Special:GlobalPreferences)

> Can be configured via CLI in the unlikely event someone is running their own retrace server etc.

That wouldn't be feasible when a user accidentally enters an incorrect API key.
