### ISSUE TITLE
Integrate with GNOME privacy settings panel

### ISSUE THREAD

**Issue by elad661** [abrt/gnome-abrt#74]
As discussed in issue #69 and the Fedora Desktop mailing list, ABRT should send reports by default, and users should be able to disable this in the Privacy panel in GNOME.

The code is here:
https://git.gnome.org/browse/gnome-control-center/tree/panels/privacy

I'd assume the easiest way to do it is if ABRT had a gsettings key to change this setting, then it's just a matter of hooking a GtkSwitch to the gsettings key (easy), and only show it if ABRT is installed on the system (might be a little bit more tricky, but not too hard).

This setting should, if possible, be on a per-user basis.

**Comment by allanday** [comment]
I've requested that a setting for automatic bug reporting be added to gnome-control-center - see https://bugzilla.gnome.org/show_bug.cgi?id=742375 . Once that's been added, it would be good to remove the automatic crash reporting message dialog, since it shouldn't be needed any more.

**Comment by hadess** [comment]
I believe we can say that this has been done. The gnome-control-center panel changes have landed, and all the patches for abrt (the daemon and the applet) have been merged. The only thing blocking it from Fedora is the absence of privacy policy.
