### ISSUE TITLE
Use GTask to download HTML page title

### ISSUE THREAD

**Issue by hadess** [abrt/gnome-abrt#96]
gliburltitle.py uses GSource to avoid synchronous calls when downloading the title. Using GTask and g_task_run_in_thread() would make it easier to implement.

**Comment by ernestask** [comment]
Another problem is that the actually useful functions (`g_task_run_in_thread()`) are not introspectable. I’m thinking missing annotations somewhere.

**Comment by ernestask** [comment]
And it looks like it’s the `task_func` parameter in particular. Will try creating a MR for GLib.

**Comment by ernestask** [comment]
Left a comment on https://gitlab.gnome.org/GNOME/glib/issues/668, since there are patches floating around that do exactly that.
