### ISSUE TITLE
Include problem title in problem list

### ISSUE THREAD

**Issue by allanday** [abrt/gnome-abrt#99]
In the mockups [1], each list row contains four items of information - each in one corner of the row. Right now, gnome-abrt doesn't have an item in the bottom-right corner, which leaves the list rows looking unbalanced. Adding the problem title would make the list look complete. It would also be useful! :)

[1] https://wiki.gnome.org/Design/Apps/Oops?action=AttachFile&do=get&target=Oops.png

**Comment by rluzynski** [comment]
I asked Allan what he means by a *problem title* and he explained that this is a text displayed in `lbl_reason` and based on the contents of `problem['type']`. Its value may be one of:

* `"Unexpected system error"` if a problem type is `'Kerneloops'`;
* `"Fatal system failure"` if a problem type is `'vmcore'`;
* `"{0} quit unexpectedly"` (`{0}` is replaced with the application name) if a problem type is other and the application name is known;
* `"{0} problem has been detected"` (`{0}` is replaced with one of: `Kerneloops`, `C/C++`, `Python`, `Ruby`, `VMCore`, `AVC`, `Java`) if a problem type is other and the application name is unknown.

@jfilak, please verify if this is correct, for example if I have not missed or misunderstood anything.

@allanday, please propose how to reword those texts and how they map into the examples from the mockup: `Crashed`, `Misbehavior`, `Failure`.

**Comment by jfilak** [comment]
The list is complete, you didn't miss anything.

**Comment by allanday** [comment]
> I asked Allan what he means by a problem title and he explained that this is a text displayed in lbl_reason

Having consulted the mockups, I might have been wrong about that.

The idea is that one string should show the component, and another should show the problem type:

https://raw.githubusercontent.com/gnome-design-team/gnome-mockups/master/problem-reporting/png/problem-reporting-app.png

Crashed, Misbehaviour and Failure are just suggestions: you could create your own categories depending on what information is available. For example: System Crash, Application Crash, Component Misbehaviour.

**Comment by jfilak** [comment]
@rluzynski ABRT detects Application Crashes - C/C++, System Crashes - vmcore, System Failures - koops. Python, Java and Ruby are problematic because an uncaught exception does not necessarily causes the application to crash and we have cannot find out whether the application crashed or not. In the future, setroubleshoot should report AVCs to ABRT - System Misbehavior ?

**Comment by rluzynski** [comment]
Let's start with this simple change. May need rewording but this will be easier.

@allanday, are you able to retrieve my branch and test my latest commit?
